version: '3'
services:
  dnsmasq:
    container_name: "dns-service"
    environment:
      HTTP_USER: "root"
      HTTP_PASS: "root"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: dnsmaasq:latest
    volumes:
      - "/etc/dnsmasq.conf:/etc/dnsmasq.conf"
    logging:
      options:
        max-size: "16m"
        max-file: "3"
    ports:
      - "5380:80"
      - "53:53/udp"
